### ISSUE TITLE
EXAM Test Failures

### ISSUE THREAD

**Issue by SManAT** [valueerrorx/life-exam#45]
We detected some issues with the EXAM Mode in LIFE.
(Servus Thomas)

- Geogebra can only save local to Downloads. But Downloads are forbidden to browse during Exam.
Is it possible to default save to Desktop (SHARE)?

- ODT Files open with Calligra Words, better open with LibreOffice?
Is it possible?

Any help needed.

btw, LIFE is best **Daumenhoch**

**Comment by valueerrorx** [comment]
thx...  i will review the geogebra problem asap...  geogebra is a webapp that runs in chrome.. so it's a little bit difficult to handle.. 


odt files are currently associated with calligra words because it is a kde application that knows about qdbus subsystem which is used to AUTOSAVE without interrupting the students...  

will add this to my loooong list of ToDo's ... thx

**Comment by SManAT** [comment]
ty, thats clear.
No worry about, keep that good work up!
